name: ci
run-name: Test-CI
on: [push]
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, world!"
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: bash .bash/automate.bash
  # triger-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger
  #       run: bash .bash/trigger.bash
