name: workflow-docker-build
run-name: workflow-docker-build
on: [push]
jobs:
  # hello-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Hello
  #       run: echo "Hello, world!"
  build-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: bash ./.bash/automate.bash ${{ secrets.DOCKER_HUB_USERNAME }} ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Trigger to k8s-workshop
        run: bash .bash/trigger.bash ${{ secrets.GIT_PAT }}
