name: workflow-docker-build
run-name: workflow-docker-build
on: [push]
jobs:
  # hello-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Hello
  #       run: echo "Hello, world!"
  build-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: bash ./.bash/automate.bash
  # triger-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger
  #       run: bash .bash/trigger.bash
